### ISSUE TITLE
Update Wiki's Branch Naming Conventions & GitFlow Usage

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/case-management#14]
Our wiki (or some other definitive source) regarding this matter needs to be updated.

I agree with the feedback here https://github.com/ca-cwds/case-management/pull/11#pullrequestreview-68138673:

* Use `dash-case` for branch names
* drop [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) branch prefixes (e.g.; `feature`, `release`, `hotfix`, ...)

More importantly, our [wiki](https://github.com/ca-cwds/case-management/wiki/Source-Control-Strategy) is a bit misleading as we aren't really doing gitflow.

**Comment by eckdanny-osi** [comment]
I've been naming branches `feat/my-cool-new-thing`. Happy to drop the _prefix_.

^ Got into that habit working with collaborators that use the [`gitflow`](https://github.com/nvie/gitflow) git extensions or GUI's with gitflow macros (e.g.; [sourcetree](https://blog.sourcetreeapp.com/2012/08/01/smart-branching-with-sourcetree-and-git-flow/), [tower](https://www.git-tower.com/help/mac/integration/git-flow), ...) which _actually_ add the branch "type" to the branch name (e.g; `<type>/<name>`)

**Comment by edgibbs** [comment]
I am still adjusting to non-command line git, but I'll update the wiki.

**Comment by edgibbs** [comment]
They've been updated, closing.
