### ISSUE TITLE
Pull request - Build Fails

### ISSUE THREAD

**Issue by RamuKammagani-osi** [ca-cwds/case-management#181]
Pull request build fails as it still looks for the files in master instead looking at the pull request branch.

**Comment by RamuKammagani-osi** [comment]
<img width="788" alt="screen shot 2018-01-22 at 3 14 22 pm" src="https://user-images.githubusercontent.com/30534124/35249484-10a2c2d8-ff87-11e7-8c88-247dbd51fe78.png">



It still looks for the spec/clientid_controller_spec.rb file instead looking at 
spec/clients_controller_spec.rb file  which you can see in PR- #178

**Comment by eckdanny-osi** [comment]
The CodeClimate `cc-test-reporter` is finding something that is stale and shouldn't be there.

Looks like we need a simple [`deleteDir`](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/) in our pipeline. I thought we'd been starting from a clean workspace with every build. I guess not.

The test reporter was disabled in #182. We'll re-enable after we're cleaning up the jenkins workspace between builds.
