### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by Sushmareddy-OSI** [ca-cwds/case-management#188]
Build fails , cannot start using 'foreman start -f Procfile.dev'  

<img width="1119" alt="screen shot 2018-01-23 at 3 37 47 pm" src="https://user-images.githubusercontent.com/30534122/35306644-b5c77110-0053-11e8-89fa-f10a8a703c80.png">

**Comment by edgibbs** [comment]
Yeah, trying to get it back to consistent with environment variables right now, if that doesn't work I can help troubleshoot.  And may need to run the rails server locally for now.

**Comment by Sushmareddy-OSI** [comment]
<img width="746" alt="screen shot 2018-01-23 at 4 17 41 pm" src="https://user-images.githubusercontent.com/30534122/35307723-01cff92e-0059-11e8-83cc-d2f76c985a0c.png">

Tried doing commenting case-web 
Also tried running rails server locally

<img width="631" alt="screen shot 2018-01-23 at 4 19 09 pm" src="https://user-images.githubusercontent.com/30534122/35307806-6cd6464c-0059-11e8-964e-046fbc163a3f.png">

same error after yarn install

**Comment by RamuKammagani-osi** [comment]
@Sushmareddy-OSI i'm closing this as this is resolved.

**Comment by RamuKammagani-osi** [comment]
npm uses the Cache memory when the packages was installed and throws an error while loading node-sass library. Resolved it
