### ISSUE TITLE
Docker image must have nodejs runtime

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/case-management#8]
Docker image must have `nodejs` runtime to support the build process. Patch the `Dockerfile` so that the image has `node` and `yarn`.

**Comment by eckdanny-osi** [comment]
You can take a look at the `Dockerfile` from de4940a72c7319449440eba8fb647f930bafc404 in the [rails-5-1-webpack-react](https://github.com/ca-cwds/case-management/blob/rails-5-1-webpack-react) branch for reference.

**Comment by eckdanny-osi** [comment]
Also here's the CALS base image [`Dockerfile`](https://github.com/ca-cwds/CALS/blob/development/docker/dev/app/cals-base/Dockerfile)

**Comment by RamuKammagani-osi** [comment]
@eckdanny-osi i have updated the Dockerfile and now our docker image has the nodeJS, So please take a look and verify so that we can close this issue. Thanks

**Comment by eckdanny-osi** [comment]
or #21

**Comment by eckdanny-osi** [comment]
Resolved by #21. closing.
